package jp.ac.uryukyu.ie.e205703;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
public class GameTest {     
    @Test void check_num() {
        int seikai = 20;
        Game confirm = new Game();
        assertEquals(seikai,confirm.cal("D4"));
    }
}
    
